apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- if not .Values.skipLabels }}
  labels:
    {{- include "gadget.labels" . | nindent 4 }}
  {{- end }}
  name: {{ include "gadget.fullname" . }}-role
  namespace: {{ include "gadget.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    # update is needed by traceloop gadget.
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
